# Generated by Django 3.2 on 2021-05-02 17:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lolp1', '0017_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date_posted'),
            preserve_default=False,
        ),
    ]
